name: unicode_todo_app
description: A ToDo app with Flutter, Firebase, Hive, and localization support (English/Arabic).

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  easy_localization: ^3.0.7
  flutter_animate: ^4.5.0
  workmanager: ^0.5.2

  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
